# web port
server.port=8081
# no web
#spring.main.web-environment=false

# log config
logging.config=classpath:logback.xml


# xxl-job admin address 调度中心地址，多个','分割。向调度中心注册自己
# 集群环境，各节点地址需一致
xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
### xxl-job, access token
xxl.job.admin.accessToken=default_token
# xxl-job timeout by second, 和调度中心通信超时时间
xxl.job.admin.timeout=3

# xxl-job executor 执行器名称
# 集群环境，各节点名称需一致
xxl.job.executor.appname=xxl-job-executor-sample
# xxl-job executor registry-address: 执行器注册地址，未配置时，使用xxl.job.executor.ip:xxl.job.executor.port配置
xxl.job.executor.address=
### xxl-job executor server-info
xxl.job.executor.ip=
xxl.job.executor.port=9999
### xxl-job executor log-path
xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
# xxl-job executor log-retention-days 日志保留天数
xxl.job.executor.logretentiondays=30
